sonar.projectKey=puj-course_FIS_2610_3517_G2
sonar.organization=puj-course
sonar.projectName=FIS_2610_3517_G2
sonar.sources=backend/app
sonar.tests=backend/tests
sonar.exclusions=frontend/**,jupyter/**,scripts/**,**/*.html,**/*.css,**/*.md
sonar.coverage.exclusions=frontend/**,jupyter/**,scripts/**,**/*.html,**/*.css
sonar.python.version=3.10
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.sourceEncoding=UTF-8
