sonar.projectKey=puj-course_FIS_2610_3517_G2
sonar.organization=puj-course
sonar.projectName=FIS_2610_3517_G2
sonar.sources=backend/app,frontend/src
sonar.tests=backend/tests
sonar.python.version=3.10
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.sourceEncoding=UTF-8
