sonar.projectKey=puj-course_FIS_2610_3517_G2
sonar.organization=puj-course
sonar.projectName=FIS_2610_3517_G2
sonar.projectVersion=1.0

# Fuentes
sonar.sources=backend/app,frontend/src
sonar.tests=backend/tests
sonar.sourceEncoding=UTF-8

# Exclusiones
sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/migrations/**,frontend/dist/**
sonar.exclusions=**/models/**

# Coverage de Python
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.python.version=3.10
